### ISSUE TITLE
Request for virtual keyboard

### ISSUE THREAD

**Issue by 0100101000101** [libretro/vice-libretro#175]
It's possible add simultaneous key press on virtual keyboard?

**Comment by sonninnos** [comment]
I've thought about it, but haven't yet bothered, because the need is tiny, and the change won't be that tiny. Combinations can be done with the mappings already, and the mappings can be used with the VKBD.

Like I have mapped RUN/STOP to L2, and keeping that pressed while pressing RESTORE on the VKBD works fine. I've only encountered one game so far (Indoor Sports) that requires pressing F1+F3 or F5+F7 to return to the main menu, and those can be done with the above method.

But do present more examples if you have them and I'll think about it.

**Comment by 0100101000101** [comment]
Works good that way. Lode Runner requires simultaneous press of CTRL and a key like A, R, etc, for certain functions, so I asked. Thank you.
