### ISSUE TITLE
When loading State, wrong disk is inserted

### ISSUE THREAD

**Issue by MajorWilly** [libretro/vice-libretro#184]
I made a Save State on Sam's Journey when I was on Disk 2. When I reloaded the State, Disk 1 was inserted and eventually crashed.

I run the game from a .m3u file. All d64 unzipped.

**Comment by MajorWilly** [comment]
Also, is it supposed to show the name of the disk in the status bar ? I haven't seen this happen on PUAE. This would be useful to know which disk you're inserting before "closing the tray", assuming that the end of the filename fits on the screen, because some games crash if the wrong disk is inserted.

**Comment by sonninnos** [comment]
The emulator does have the right disk in the state, but RA should be notified about it somehow too. No idea if it can be done. Anyway better change to CRT versions when possible, like in this case.

I haven't yet gotten around to show the filename in the statusbar on PUAE too. But still it would only pick up the inserted disk after closing, since the information comes from the emulator, not RA, so no use there.

**Comment by MajorWilly** [comment]
Yeah, I should use CRT when possible and come to think of it, 'Sam's Journey' has a save game option so it should save to disk as the disks are unzipped. I don't know why I didn't try that ! (I'll have to remember the disk I was on when making savestates for multidisk games that have no CRT or D81).

It was actually Retroarch telling me the filename of the disk before closing the tray which is very helpful. They must have added that feature fairly recently. I'm not sure what the use of the filename in the core statusbar is for now though ?

**Comment by MajorWilly** [comment]
I just tried something on PUAE. A multidisk game (Bubble & Squeak) with a M3U but I didn't add (MD) to the filename so only 1 disk was inserted. After I inserted disk 2 I made a savestate, exited the game, reloaded it then Load State. When I lost all the lives it asked me to insert Disk 1. So the correct disk (Disk 2) was inserted when loading the State ?

**Comment by sonninnos** [comment]
Yes, AFAIK both cores do have the same disk inserted when loading a state, because that information is saved in the state. But RA just will/can not update its index accordingly, so it needs some manual jiggling to get the right one inserted. Too bad for games that just assume the right disk is in when they start loading/saving.

**Comment by MajorWilly** [comment]
So it works correctly on PUAE but not VICE ?

**Comment by sonninnos** [comment]
It does not work "correctly" on either, and works the same on both. Which is: Statefile inserts the right disk, but RA don't know the disc changed.

1. Saved while Disc 2 inserted in RA
2. Load state
   - Disc 2 is internally inserted
   - RA correctly thinks Disc 2 is still inserted

And after restart:
1. Load state while RA is on Disc 1
    - Disc 2 is internally inserted
    - RA still thinks Disc 1 is inserted

**Comment by MajorWilly** [comment]
Not sure I understand this fully. Sorry if it's annoying you.

With PUAE, if I load a multidisk game and at the Cracktro at the beginning, I manually insert Disk 2 and do a savestate. If I restart the game and load the savestate, click the cracktro to continue it crashes because Disk 2 is inserted, which is correct.

With VICE if I do the same thing (manually change to disk 2 at cracktro and savestate). Restart the game and load the state. When I continue from the cracktro it loads OK (but it should crash because I saved with Disk 2 inserted).

**Comment by MajorWilly** [comment]
I remember that VICE uses a different savestate method so is it actually saving all information (like which disk was inserted) ?

**Comment by sonninnos** [comment]
Hmm, looks like there indeed is something odd with VICE.

- I created 2 disks, named EMPTY1 and EMPTY2, put them in a M3U
- Inserted EMPTY2, listed contents, saved state
- Restart, load state
- First it looked like the disk changed with the savestate, because when doing F3 on the disk, EMPTY2 was showing correctly
- But then I did F1, and after that F3 shows EMPTY1
- WAT

VICE is not saving the contents of the disk to the savestate, that would break D81 saves.

**Comment by MajorWilly** [comment]
When you say it's not saving the contents of the disk, you mean what disk is actually inserted ? This would explain what I typed two posts up. Is it saving other information like model, SID etc. And it doesn't seem to care if Warp mode is on when loading #183 .

As I say, PUAE saves the "state" including the disk number but Vice doesn't.

**Comment by sonninnos** [comment]
No, contents as in the whole disk inside the state. It could do it, but does not. Carts will be saved completely in the state no matter what. Warp mode plays no part in what goes in or out the savestate data. And that essential memory based statefile contribution also plays no part in what data is saved or retrieved internally in VICE.

But the VICE statefile creating function has 2 options: 'save_roms' and 'save_disks'. Both are now off, because the size will be the smallest, and looks like enabling 'save_roms' solves the issue.

**Comment by MajorWilly** [comment]
You know best ! Some disks don't display any contents (like disk 2 of some rainbird adventures etc.). I assume that won't affect it ? (and non-DOS filesystem Amiga games).

Is there any sort of check that should disable Warp (if it's on) when loading a state, otherwise the game plays at the fastest possible speed with no sound ?

**Comment by sonninnos** [comment]
Warpmode fix at state load incoming also.

**Comment by MajorWilly** [comment]
Still doesn't work I'm afraid. Doesn't seem to restore the disk that was inserted (ie. Disk 2) like PUAE does.

**Comment by sonninnos** [comment]
Yep, I tried with Maniac Mansion and noticed the fix did not work.

**Comment by MajorWilly** [comment]
Sorry, I didn't see your 2nd Edit. The new commit does work like you said but there are problems. 1) Like you said, the wrong disk is shown in the status bar and 2) It only seems to work when True Drive Emulation is ON. If it's OFF then it's the same as before.

I'll vote to revert this to what it was originally. If it crashes then that means the wrong disk is inserted. It's not much of a problem. Don't know how PUAE manages it though ?

**Comment by sonninnos** [comment]
Ok, suits me. I'll just need to figure out how to disable it from PUAE. As based on the state size, it appears to only save the drive position and state, and the path to the image.

Can be a can of worms though, but yes the disk changing power should be with RA alone.

**Comment by rsn8887** [comment]
Shall I revert https://github.com/libretro/vice-libretro/pull/187/commits/372747fcdccaa7d7679ba1013d6c4db2a7061a94 ?
