### ISSUE TITLE
Feels a bit sluggish during Warp

### ISSUE THREAD

**Issue by WindyWinston** [libretro/vice-libretro#259]
I noticed when the Warp is happening it feels a bit sluggish if you try to do anything. For example, if you open the Retroarch menu or bring up the on-screen keyboard or statusbar, you need to hold down the key/button for it to register.

**Comment by sonninnos** [comment]
Yes, because it skips frames for the internal warp to actually do what it is supposed to. Sure it probably can be tuned some more, but I tried to go for the maximum speed without it becoming totally unresponsive. And because one rarely really needs to use VKBD/statusbar during loading.

Is this really a problem that needs attention, since in practice it means the warp speed will take a hit, and currently it still lags behind the speed that fast-forward can achieve, even when the warp mode is based on skipping audio rendering (which should give more speed, but I didn't figure out why/how it does not after spending a lot of time on it)..

**Comment by WindyWinston** [comment]
Isn't really much of a problem. I noticed it when I ran a demo, I brought up the on-screen keyboard to press 'reset' (so I could list the disk contents) and found it laggy trying to navigate to the reset button.

**Comment by sonninnos** [comment]
I'll do some more testing at some point to see if it could be more responsive without sacrificing too much speed.

**Comment by WindyWinston** [comment]
Did it use frameskip originally then ?. Maybe another sub-option for Warp without so much frameskip (the way it used to react), and leave the current Warp as 'maximum'. (Only if it's not too much hassle, otherwise don't bother).

**Comment by sonninnos** [comment]
Yes, the internal warp can not work without skipping frames. The issue is the amount of VICE frames in a frontend frame. I much much prefer optimizing the one-size-fits-all-value instead of adding more options.

**Comment by WindyWinston** [comment]
Vaguely related, I found a minor oddity. The HSVC collection has PRG versions of their SIDs (Example attached). If JiffyDOS is on and you load one of these zipped then it doesn't stop warping. If it's unzipped then it loads OK. Also, it doesn't load the Zipped PRG when 'Autostart = OFF'.

I may have got some of this muddled up.

[Rambo - First Blood Part II [SID].zip](https://github.com/libretro/vice-libretro/files/4740939/Rambo.-.First.Blood.Part.II.SID.zip)

**Comment by sonninnos** [comment]
I don't get it and can't reproduce. It doesn't even start to warp here, like it shouldn't, because it is not a floppy/tape.

Also wanting to not start memory injected PRGs/CRTs makes very little sense, and having those kind of files in a playlist (running a ZIP is equal to running a M3U) already is pretty kludgeish, so that does not seem important enough to "fix" at all.

**Comment by WindyWinston** [comment]
> That VICE autostartwarp is pretty much useless now compared to autoloadwarp, so maybe it should be removed altogether.

You're thinking of removing the autostart warp in favour of the autoload warp ?

**Comment by sonninnos** [comment]
Of course. It is much more reasonable than trying to fix autostartwarp and have both.

**Comment by WindyWinston** [comment]
But the autoload warp warps all loading including games and demos that load on the fly. We won't be able to just warp the beginning load sequence.

**Comment by sonninnos** [comment]
Fine, whatever. I'll just force disable it with PRGs and CRTs then.

**Comment by sonninnos** [comment]
I can't figure out a way to reduce the sluggishness without also heavily reducing the warp speed, but I can increase the warp speed a little without much difference in sluggishness..

**Comment by WindyWinston** [comment]
So is the current Warp past the point of no return, meaning that it can't go back to what it was originally ? So like I said above, have the original warp (that didn't feel sluggish) and the new aggressive version.

**Comment by sonninnos** [comment]
Sure it can, but it will be barely faster than no warp.

**Comment by sonninnos** [comment]
Reset hotkey sorts that problem somewhat. I feel a slightly longer button press beats a lot slower warp, especially with tapes.

**Comment by WindyWinston** [comment]
Yeah go for it. Did you say that you also blacklisted PRG/CRT from activating the warp ?

**Comment by sonninnos** [comment]
Aye, that one is sorted and ready for final tests.
