### ISSUE TITLE
Minor issue with Status Bar, Firestick 4K

### ISSUE THREAD

**Issue by WindyWinston** [libretro/vice-libretro#260]
I was bored so I thought i'd try a few Retroarch cores on the Amazon Firestick 4K. This Vice core runs great (as long as it's FastSID) but the StatusBar doesn't seem to be acting right. The Joystick number highlight appears to be missing and it always says 0 in the FPS red light.

![1](https://user-images.githubusercontent.com/60177795/84037188-2342f280-a996-11ea-8f96-0652ef65af3d.png)
![2](https://user-images.githubusercontent.com/60177795/84037199-26d67980-a996-11ea-9251-48e3df716e35.png)

I just realised that the screenshots are original size.

I don't expect a fix for this, just wondered if you had any ideas why this happens ? It uses Android, not sure what version but my other Android device displays it fine. The Amiga core displays the FPS light OK and the joystick numbers (but they don't have highlights on the selected joystick number like the Vice core does which is correct).

**Comment by sonninnos** [comment]
Not a slightest clue how that active port color inverse is possible to not work..

The FPS counter display methods are not comparable at all between VICE and UAE (not the way it is drawn and not the way it is calculated), but that zero value clearly has something to do with `RETRO_ENVIRONMENT_GET_PERF_INTERFACE` not working properly, since nowadays the value is based on that in order for the FPS counter to not be locked at refresh rate during Warp/FF.

I'll try to restore the previous counter method as a fallback while I'm at it. I already sorted the sticky warp issue.

**Comment by WindyWinston** [comment]
Your vsync commit has fixed the 0 fps on the status bar with the Firestick 4K ! Good job. It actually seems more stable than the PUAE one (On Android at least).
