### ISSUE TITLE
Apply approximation of current host keyboard layout to C64

### ISSUE THREAD

**Issue by ntninja** [libretro/vice-libretro#301]
So, trying VICE's `x64` I found that it immediately started with German keyboard layout loaded on my system (with a German KBD layout variant). This comment in https://github.com/libretro/RetroArch/issues/8303#issuecomment-464472759 makes it pretty clear that RetroArch expects Cores to perform a best-effort keycode to keysym mapping themselves where applicable.

In particular Vice already ships with some mapping tables for a few layouts upstream:

```
sdl_pos_da.vkm
sdl_pos_de.vkm
sdl_pos_fi.vkm
sdl_pos_no.vkm
sdl_sym_de.vkm
sdl_sym_nl.vkm
```

No idea whether these actually correspond to anything ever shipped on hardware C64s, but they are pretty useful nonetheless.

(Ideally, it would somehow generate a layout based on checking whether the currently layout supports all required characters and mapping them in a way Vice can understand, but that would be much harder than just reusing some known-good layouts.)

**Comment by sonninnos** [comment]
Yep, since libretro do not transfer that information, the core should handle it. The only downside is in the current method of handling all keymaps for all different VICE cores, which makes including additional maps a chore. The user-defined option is added for that reason.

But since VICE only has those different maps available for C64 anyway, maybe it isn't that bad. Otherwise it really would need to be rewritten to be able to import said files without manual labor. At least QWERTY, QWERTZ and AZERTY would be reasonable to have selectable directly.

Indeed none of my Finnish C64s have any umlauts on the keys like it suggests in the `_fi.vkm`..

**Comment by sonninnos** [comment]
`raw` and `dinput` drivers in RA no longer send different keys depending on the OS locale.

I feel that the currently available user-defined map options are enough to handle these needs, thus I'll close this.
