### ISSUE TITLE
Core options question - zip file overrides

### ISSUE THREAD

**Issue by cmitu** [libretro/vice-libretro#353]
Hi,

I'm trying to run a 2disc game from a single `.zip` archive, using `vice-x64`. The game needs TDE (won't load without it), if I enable it in the core options is loads fine (from the 1st disc).

However, if I want to turn on TDE only for this game, using a game options file saved with TDE=On while leaving TDE=Off globally, the options are not applied when loading the game again from the `.zip` file. 

Looking at the log fie, I see a few errors regarding core options when the first `.d64` image is loaded:
```
[libretro INFO] retro_set_environment: GET_CORE_OPTIONS_VERSION failed, not setting CORE_OPTIONS now.
[libretro INFO] retro_set_environment: GET_CORE_OPTIONS_VERSION failed, not setting CORE_OPTIONS now.
```
Full log file is [here](https://pastebin.com/raw/3WyE2FG8).

Is this kind of configuration supposed to work ? Does it need additional configuration maybe ?

**Comment by sonninnos** [comment]
Hmm, game-specific core options working fine here, zipped or no zipped, and even if the file inside the zip is named differently than the zip. The zip filename is picked as the content and the core has no idea about the options being global or not. Also no matter if TDE is globally enabled and game-specific is disabled or vice versa.

Are you totally sure that the opt-file really does have TDE enabled? This says it is not:
```
[INFO] Per-Game Options: game-specific core options found at C:\Users\mitcr01\Desktop\roms\RetroArch\config\VICE x64sc\Oil Imperium.opt
...
[INFO] [Environ]: GET_VARIABLE vice_drive_true_emulation:
	disabled
...
[libretro INFO] Resource DriveTrueEmulation = 0
```

Those set_environments infos are a red herring and related to frontend calling set_environment multiple times in a weird time. It will ultimately succeed, otherwise there would be no core options at all. Maybe it could be cleaned up if the legacy support for old core options version is removed..

**Comment by cmitu** [comment]
You're right, for some reason I though I've saved the game options, but I must have saved them with the wrong option.
Sorry for the noise - looks to be working fine.
