### ISSUE TITLE
Vice PET only autostarts content with model 80XX

### ISSUE THREAD

**Issue by cucholix** [libretro/vice-libretro#359]
Latest Vice PET core as 6-march 2021 only autostarts content when launched from playlist with 80XX models, other models need you input the command to start the game, it happened to me on Switch, but @sonninnos confirmed it happens on other platform. Worth noting that it doesn’t happen in standalone, not sure when exactly this bug start to happen or if it was always like that. 

The 80XX model split the picture like this:
![D438877F-4663-4D05-9E10-3C8998CFA0C4](https://user-images.githubusercontent.com/16081693/110238963-3386fe80-7f23-11eb-9775-77cd4f26a365.jpeg)(Breakout)

So most games are unplayable under 80XX.

By comparison 2031 model for example display the games correctly:
![6D36845D-C8DC-404B-8CE6-3D9C61A95F2A](https://user-images.githubusercontent.com/16081693/110239101-f707d280-7f23-11eb-915f-ece5a75557d0.png)

**Comment by sonninnos** [comment]
Looks like this issue will sort itself with 3.5, since 3.3 standalone actually suffers from it after all.

Replicated by changing the model via the menu and then trying to autostart via the menu. Autostart stops working after the model change reset.

Standalone starts straight up from the saved config, as in no reset required, but this core starts with the defaults, and then resets with the core options configuration. So something is simply not resetting properly.

**Comment by cucholix** [comment]
Tried with updated core, and the image still appears split with model 80XX

**Comment by sonninnos** [comment]
That is what model 80XX does.. This didn't fix that, because it can't be fixed. This fixed the non-default models autostarting properly.

**Comment by cucholix** [comment]
2031 model doesn’t autostart on my end

**Comment by sonninnos** [comment]
Works fine here.

**Comment by cucholix** [comment]
Tried with every model available, and only 80XX autostart, but has the split screen issue

**Comment by sonninnos** [comment]
Log might make things clearer, as usual.

**Comment by cucholix** [comment]
Was preparing the log for you and it happens it now it works hah.
Maybe it didn't updated properly :)
