### ISSUE TITLE
Vegetables Deluxe crash

### ISSUE THREAD

**Issue by IAmBoring** [libretro/vice-libretro#384]
This game is currently free due to the pandemic.
https://doublesidedgames.com/shop/commodore/commodore-64/vegetables-deluxe/

Everything works okay until you get in-game.

1. Enter the libretro menu, don't change anything and return to core, game will break and take you to some type of BASIC looking menu with no text.

2. Don't enter the UI menu but turn on / off libretro fast-forward button, same crash.
3. Various methods of save / load state can trigger same crash too.

If you never enter menu, game seems perfect. Libretro pause / resume does not trigger crash.

x64 Fast, Pal. Cartridge v1.0.

**Comment by sonninnos** [comment]
Looks like the CRT version of the game is broken so that it will halt pretty much on every keyboard key press. PRG and cracked version does not do that. Same happens with standalone VICE, so there is nothing to be done here.

Anyway regardless of the version, you should update RetroArch, because current version no longer sends for example Space to the core when Space is used to Fast Forward, or F1 to the core when trying to open menu, or any other hotkey. Which means the CRT version should be usable too, as long as you don't accidentally press some wrong key which is not a hotkey.
