### ISSUE TITLE
Map second player buttons using .opt files...?

### ISSUE THREAD

**Issue by fastpop72** [libretro/vice-libretro#426]
I use .opt files to assign keys to joypad buttons... like this:

vice_joyport = "2"
vice_joyport_type = "1"
vice_mapper_a = "RETROK_SPACE"
vice_mapper_b = "---"
vice_mapper_down = "---"
vice_mapper_l = "---"
vice_mapper_l2 = "---"
vice_mapper_left = "---"
vice_mapper_r = "---"
vice_mapper_r2 = "---"
vice_mapper_reset = "---"
vice_mapper_right = "---"
vice_mapper_select = "TOGGLE_VKBD"
vice_mapper_start = "RETROK_RETURN"
vice_mapper_up = "---"
vice_mapper_vkbd = "---"
vice_mapper_warp_mode = "---"
vice_mapper_x = "---"
vice_mapper_y = "---"

It's possible to map buttons for the second player too?

For example in Gauntlet to use magic i have to assign "RETROK_SPACE" to button A of Joypad1 and "RETROK_F1" to button A of Joypad2.

Thanks.

**Comment by sonninnos** [comment]
No, not going to happen. The sufficient way of doing this currently is to map all required buttons to the shared RetroPad with those options, and then simply adjust Quick Menu > Controls > Port x Controls so that you can't press each others magic keys.

For example put P1 magic to L1 and P2 to R1, and then switch P1 A to press L1 and P2 A to press R1.

I'll close this.
