### ISSUE TITLE
Touchscreen virtual keyboard and zoom oddities

### ISSUE THREAD

**Issue by zzedmore** [libretro/vice-libretro#431]
Hi, the touchscreen virtual keyboard feels off with any amount of zoom. Pressing a key on the touchscreen triggers a different place. The more zoom the worse it gets. For instance, with Automatic zoom (maximum), pressing the Up, 
down or left cursor triggers the right cursor.. Basically, all keys near the outside edge of the keyboard dont press the correct key. This is the first time i've used the touchscreen for the virtual keyboard so not sure when this began occurring. (Android 11).

For reference, I checked the PUAE core's virtual keyboard with zoom and that responds correctly. I can rule out the beer 😄 (i think).

**Comment by sonninnos** [comment]
Does the "Zoom Mode Crop" option make any difference with it and/or how about with manual cropping?

**Comment by zzedmore** [comment]
Yes it also seems to happen with 'zoom mode crop - horizontal, vertical etc.', at it's worse with maximum zoom. (And manual zoom, the more you crop the worse it gets.)  If I turn zoom off, it seems to work fine.

**Comment by sonninnos** [comment]
This is rather annoying, since doing the exact same testing with this and PUAE, I can't replicate anything odd with the pointer regarding VKBD keys at different zoom levels. The test is drawing a pixel on the exact pointer point, and it follows VKBD keys as it should. So the problem is somewhere else.

I can try some shootings in the dark soon which do not seem to make my tests any worse at least.

And for some magical reason now that I tried to use the core on my Android phone, there are no VICE cores to download, only Frodo and PUAE, and 
```
Download of 'info.zip' failed: Internal error.
```
And this is with RetroArch Plus from the store..

**Comment by zzedmore** [comment]
The core info.zip (and cores) download fine for me. I get my Retroarch from -

http://buildbot.libretro.com/nightly/android/

**Comment by sonninnos** [comment]
Okeydoke, I did some test changes, so please keep me posted once the build is ready.

**Comment by zzedmore** [comment]
That seems to have fixed it! Thankyou. 😄

**Comment by sonninnos** [comment]
Yeehaa, first hit, not bad for a shot from the hip!
