### ISSUE TITLE
Would like to contact sonninos

### ISSUE THREAD

**Issue by Kugelblitz360** [libretro/vice-libretro#441]
Greetings from Germany! I see that you are doing LOTS of **good** patches for libretro-vice and for some I would like to understand your intentions and goals. I would like to writer proper documentation. Also I would like to know whether you want to rebase to Vice 3.6 or stay with 3.5 for the time being. Sorry to misuse the issue tracker for this, can't find a Email here, at your github, your soundcloud or your webpage... :-) Mine is boris at schno.net. Thank you!

**Comment by sonninnos** [comment]
Thanks, cheers! I just want to help making Commodore great again, as in make usability and features as faithful/accurate/reasonable as possible for the most often desired gaming scope, and then some.

Documentation already exist where the other libretro ones are, but it is a few months behind. I'll be updating it soon anyway.

I had a quick look at the 3.6 changelog, and so far looks like I will skip the updating hassle, since it does not seem to bring or fix anything substantial. It would make old savestates unusable again too. But if there is something critical after all, I can always try backporting it.

The libretro Discord server can be used also, I'm there with the same name.

**Comment by elessar38** [comment]
@sonninnos How about version 3.7 which was released recently?
In case of any problems, you could add a separate core, e.g. Vice x64 current. Everyone could choose whether they want to stay with the old or the new version.
