### ISSUE TITLE
Odd lines PAL CRT settings

### ISSUE THREAD

**Issue by Jamirus238** [libretro/vice-libretro#445]
The default PAL effect that  can be  managed in standalone Vice via the odd lines settings is a bit strong, is it possible to have options for tuning/disabling that part of the CRT filter?

**Comment by sonninnos** [comment]
I'm unable to see any difference with any value of OddLinePhase, but indeed current OddLineOffset default is not optimal, and value 1000 (50%) looks nicer.

Those values can be set via `vicerc`, and currently looks like I'll only add Offset, since why bother adding options that do nothing..

**Comment by Jamirus238** [comment]
Ah yes, it's adjustable via vicerc. Was also thinking about custom palettes (mostly for NTSC), it's not in the dump file, so this isn't possible?

**Comment by sonninnos** [comment]
Apparently custom palettes aren't happening without effort due to the way embedded files are handled. I tried copying a .vpl from VICE\C64 to the same place under `system\VICE\C64`, but it did not get replaced. So I guess the only way to do it is to add a palette named "custom" and handle it separately, but not sure if all that is worth the effort considering how much the colors can be already mangled via the options..

**Comment by Jamirus238** [comment]
I suppose that options + shaders are sufficient as the region differences don't seem as big compared to say, the Atari 800. I was hoping to get some input by a certain guy who was doing some custom stuff geared towards NTSC years ago, but haven't heard back from him yet and Colodore wasn't a thing when he was active, he mostly does Atari 7800 things now.
