### ISSUE TITLE
Make virtual keyboard key presses work on both Joy 1 and Joy 2

### ISSUE THREAD

**Issue by Gazdaman** [libretro/vice-libretro#50]
Virtual Keyboard key presses only seem to work when Joy 2 is the selected input method.

When I toggle to Joy 1 using the "RETROK_KP_MULTIPLY" key mapping and then try to type on the virtual keyboard, no key press is actuated from the controller. I need to toggle back to Joy 2 to make virtual keyboard presses work.

Please make it work whether Joy 1 or Joy 2 is the selected (toggled) input.

**Comment by rsn8887** [comment]
It works with joy2 when you disable retrojoy in the menu. But then the joystick doesn't work. So to make it work with joy 2, currently, you have to disable retrojoy, use the virtual keyboard, then enable retrojoy again to use the joystick.

This explains the weird issue that pressing N on the virtual keyboard causes an automatic "Load" command sometimes. That only happens when joy 2 AND retrojoy are both enabled.

I agree this should be fixed but I don't know where the bug is at the moment.
