### ISSUE TITLE
Virtual Keyboard alternate keys

### ISSUE THREAD

**Issue by zzedmore** [libretro/vice-libretro#506]
There seems to be a minor issue with accessing the alternate keys on the virtual keyboard. Holding left/right 'Shift' will reveal the crop, aspect ratio etc. keys but when pressing them it uses the original option. For instance, holding 'Shift' then pressing ASPR changes the Joyport and CROP turns on turbo fire. It works if you press 'Shift Lock' instead.

This also happens in PUAE.

**Comment by sonninnos** [comment]
That is how it was meant to be used.

**Comment by zzedmore** [comment]
So just 'Shift Lock' is meant to access the alternate keys ? How come they are also displayed if you hold the left or right Shift keys ?

**Comment by sonninnos** [comment]
Because it was a brainfart, and because the thought process behind it was simply the press of RetroPad Y for toggling ShiftLock, since it is there by default. Mostly that Shift is used just as any other Shift, except for those hotkeys it just didn't occur to me to be able to use normal Shifts, since those weren't as globally available to be used code-wise.

**Comment by zzedmore** [comment]
I see. No worries.
