### ISSUE TITLE
Switch core keyboard problem - N key does not work

### ISSUE THREAD

**Issue by OKarter** [libretro/vice-libretro#62]
IDK if this is the correct place to submit this but while using Vice core on the Switch, the N key does not work. So i have to play all games trained :). May be true for some other keys too.

Is it only me?

**Comment by rsn8887** [comment]
Play around a bit with the control and core options in Quickmenu. I know I got it to work by changing controller type etc.

**Comment by OKarter** [comment]
Thank you RSN8887 for the effort. I've deleted retroarch and reinstalled it via homebrew browser, so that i can have default options.
1. RETROJOY0 was ON and CONTROLLER0 type was joystick by default.
2. USER1 & 2 was already set to retropad. 

I started the core pressed 'SELECT' (- on the switch) , pressed 'Y' . (brought up the keyboard), hovered over the letter n and clicked 'A'. .. It was the LOAD command with PRESS PLAY ON TAPE written below it on the screen. 

It seems that letter N was assigned to the LOAD command (with the edition of a following RETURN key).
I'll be fiddling  with the options now. I hope VICE will have a good GUI someday (on any platform) as it is a very good emulator

**Comment by rsn8887** [comment]
Are you sure you are not still loading some old configuration? Because the settings you mention are NOT the defaults as far as I know.

- It sounds like your ALT key is permanently pressed and triggers some Vice hotkey "ALT+N" or so, but how can it be?
- Make sure you really delete or rename retroarch.cfg and any other core configuration file you might have.
- And please do not use the version from the homebrew browser for testing, it is much too old. Use a recent version (today, yesterday or so) from the buildbot here
https://buildbot.libretro.com/nightly/nintendo/switch/libnx/ , and extract it to your sd card (use Winrar or any other extraction tool).

**Comment by rsn8887** [comment]
I can reproduce the problem but found a workaround:
Go to Quickmenu->Options, and set RetroPad R2->"RETROK_n".

Now you can enter the letter "n" using the R2 button (lower right shoulder button).

**Comment by ozgurkarter** [comment]
Sorry for the late answer as I had too much to do nowadays. I formatted my SD card just in case. Got the nightly build.Same again. But the workaround worked well and is fine by me.

**Comment by rsn8887** [comment]
Note: N key only doesn't work when both "joy2" AND "retrojoy" are enabled at the same time. It does work when "retrojoy" is disabled and/or "joy1" is enabled. Luckily those things can be switched rather quickly in the nuklear GUI menu that can be brought up with the "start" button.
