### ISSUE TITLE
Control over "warp mode"?

### ISSUE THREAD

**Issue by modeler** [libretro/vice-libretro#9]
Can "warp mode" be toggled (as Alt+W does in stand-alone VICE) at all please? I'm not sure how to do this as there is no menu option for it. There is the internal fast-forward option but this doesn't seem very effective in the VICE core.

Also, it doesn't seem possible to suppress warp mode when starting a program via "Load Content". The core appears to the "autostart" behaviour in VICE, which is fair enough if that's how it's meant to be. This appears to cause the video and audio to go badly out of sync when recording via FFMPEG, but I can raise a separate issue for that if required.

**Comment by r-type** [comment]
Yes an option could be add to activate/deactivate the warp mode.
have to look at.

BTW RA fastforward works for me , I use it in  conjunction of an hotkey like "f11" (to not interact with vice_keyboard binding) and with input_hold_fast_forward set to  "L".
So when loading a disk , I use to  hit "F11 + L" and then core speed is X10 and disk loading is quite fast.

**Comment by lodgerz** [comment]
hi, why if i set "WarpMode=1" on vicerc then on retroarch all c64 games runs at 60fps instead 50fps?

**Comment by fragmental** [comment]
@lodgerz how do you set WarpMode=1?

**Comment by fragmental** [comment]
I found these lines in my vicelog.txt file in the retroarch folder:
```
AUTOSTART: Turning Warp mode on
AUTOSTART: `J:\Roms\GoodGB64 v3.00 Complete 17067 ROM Set Commodore 64\GB64Ren\c\CITADEL.D64' recognized as disk image.
Main CPU: starting at ($FFFC).
Writing configuration file `./vicerc0'.
Main CPU: RESET.
Error - perkele!
Drive 8: RESET.
AUTOSTART: Loading program '*'
AUTOSTART: Searching for ...
AUTOSTART: Loading
AUTOSTART: Entered ROM at $f520
AUTOSTART: Ready
AUTOSTART: Turning Warp mode off
AUTOSTART: Starting program.
AUTOSTART: Done.
```
So it looks like it turns warpmode on and the back off again.  I generally always have Retroarch fast forward on when I'm loading a game and tapes still take forever.  Disks often take a while too.

**Comment by rsn8887** [comment]
Concerning access to the “Autostart Warp” feature, this is fixed by introducing a core option to enable/disable it in PR #76 

Concerning access to the warp feature in general: I think this could be implemented quite easily via another “mapper hotkey” core Option and a simple check that turns warp mode on as long as the key is held down.

About 60 fps while warp: this is because the sound is turned off during warp, and sound is used to sync the correct emu refresh rate. I think without sound it is limited bybvaync setting to 60 fps. If vsync could be turned off completely, it would go higher (not sure if possible in Retroarch core).

**Comment by rsn8887** [comment]
I am implementing a Warp mode button now (warp enabled while holding down button)
